version: '3.8'

networks:
  sentinelnet:
    driver: bridge

# --- NEW: Define the persistent volumes ---
volumes:
  p2p_storage_0:
  p2p_storage_1:
  p2p_storage_2:

services:
  metadata_service:
    build: ./v2/metadata_service
    container_name: metadata_service
    ports:
      - "8000:8000"
    networks:
      - sentinelnet

  p2p_node_0:
    build: ./v2/p2p_network
    container_name: p2p_node_0
    ports:
      - "8001:8001"
      - "8468:8468/udp"
    environment:
      - API_PORT=8001
      - NODE_PORT=8468
      - OWN_PUBLIC_URL=http://localhost:8001
      - OWN_INTERNAL_URL=http://p2p_node_0:8001
    # --- NEW: Mount the persistent volume ---
    volumes:
      - p2p_storage_0:/storage
    networks:
      - sentinelnet

  p2p_node_1:
    build: ./v2/p2p_network
    container_name: p2p_node_1
    ports:
      - "8002:8001"
      - "8469:8468/udp"
    environment:
      - API_PORT=8001
      - NODE_PORT=8468
      - BOOTSTRAP_IP=p2p_node_0
      - BOOTSTRAP_PORT=8468
      - OWN_PUBLIC_URL=http://localhost:8002
      - OWN_INTERNAL_URL=http://p2p_node_1:8001
    # --- NEW: Mount the persistent volume ---
    volumes:
      - p2p_storage_1:/storage
    networks:
      - sentinelnet
    depends_on:
      - p2p_node_0

  p2p_node_2:
    build: ./v2/p2p_network
    container_name: p2p_node_2
    ports:
      - "8003:8001"
      - "8470:8468/udp"
    environment:
      - API_PORT=8001
      - NODE_PORT=8468
      - BOOTSTRAP_IP=p2p_node_0
      - BOOTSTRAP_PORT=8468
      - OWN_PUBLIC_URL=http://localhost:8003
      - OWN_INTERNAL_URL=http://p2p_node_2:8001
    # --- NEW: Mount the persistent volume ---
    volumes:
      - p2p_storage_2:/storage
    networks:
      - sentinelnet
    depends_on:
      - p2p_node_0

  frontend:
    build: ./v2/frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_P2P_NODE_URLS=http://localhost:8001,http://localhost:8002,http://localhost:8003
    depends_on:
      - metadata_service
      - p2p_node_0
      - p2p_node_1
      - p2p_node_2